
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Semih Durbal
 */
public class musteriGoruntule extends javax.swing.JFrame {

    DefaultTableModel model;
    MusteriEkle musteriekle = new MusteriEkle();

    private Connection con = null;

    private PreparedStatement preparedStatement = null;

    private Statement statement = null;

    public musteriGoruntule(){
        initComponents();
        String url = "jdbc:mysql://"+DatabaseMySQL.host+":"+DatabaseMySQL.port+"/"+DatabaseMySQL.db_ismi+"?useUnicode = true&chracterEncoding = utf8";
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("Driver Bulunamadı.");
        }
        try {
            con = DriverManager.getConnection(url,DatabaseMySQL.kullanici_adi,DatabaseMySQL.parola);
            System.out.println("Bağlantı Başarılı");
        } catch (SQLException e) {
            System.out.println("Bağlantı Başarısız");
        }




        model = (DefaultTableModel)musteriTablosu.getModel();
        MusteriGoruntule();

    }


    /**
     * Creates new form musteriGoruntule
     */


    public void MusteriGoruntule(){

        model.setRowCount(0);
        ArrayList<musteriler> musteri = new ArrayList<musteriler>();

        musteri = musteriekle.musterileriGetir();

        if(musteri != null){
            for(musteriler musterilr : musteri){
                Object[] eklenecek = {musterilr.getMusteriIsmi(),musterilr.getUrunIsmi(),musterilr.getUrunBirimFiyati(),musterilr.getUrunAdedi(),musterilr.getMusteriBorcu(),musterilr.getGun(),musterilr.getAy(),musterilr.getYil()};

                model.addRow(eklenecek);
            }
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        musteriTablosu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        musteriIsimAlani = new javax.swing.JTextField();
        urunIsimAlani = new javax.swing.JTextField();
        urunFiyatAlani = new javax.swing.JTextField();
        urunAdediAlani = new javax.swing.JTextField();
        gunAlani = new javax.swing.JTextField();
        ayAlani = new javax.swing.JTextField();
        yilAlani = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        musteriDuzenle = new javax.swing.JButton();
        musteriSil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        musteriTablosu.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "Müşteri İsmi", "Ürün İsmi", "Ürün Fiyatı", "Ürün Adedi", "Müşteri Borcu", "gün", "ay", "yıl"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        musteriTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musteriTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(musteriTablosu);
        if (musteriTablosu.getColumnModel().getColumnCount() > 0) {
            musteriTablosu.getColumnModel().getColumn(0).setResizable(false);
            musteriTablosu.getColumnModel().getColumn(1).setResizable(false);
            musteriTablosu.getColumnModel().getColumn(2).setResizable(false);
            musteriTablosu.getColumnModel().getColumn(3).setResizable(false);
            musteriTablosu.getColumnModel().getColumn(4).setResizable(false);
            musteriTablosu.getColumnModel().getColumn(5).setResizable(false);
            musteriTablosu.getColumnModel().getColumn(5).setPreferredWidth(6);
            musteriTablosu.getColumnModel().getColumn(6).setResizable(false);
            musteriTablosu.getColumnModel().getColumn(6).setPreferredWidth(6);
            musteriTablosu.getColumnModel().getColumn(7).setResizable(false);
            musteriTablosu.getColumnModel().getColumn(7).setPreferredWidth(6);
        }

        jLabel1.setText("Müşteri İsmi :");

        jLabel2.setText("Ürün İsmi :");

        jLabel3.setText("Ürün Fiyatı :");

        jLabel4.setText("Ürün Adedi :");

        jLabel5.setText("Son İşlem Tarihi :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel6.setText("gun");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel7.setText("yıl");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel8.setText("ay");

        musteriDuzenle.setText("Müşteri Düzenle");

        musteriSil.setText("Müşteri Sil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(urunAdediAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                        .addComponent(urunFiyatAlani)
                                                        .addComponent(urunIsimAlani)
                                                        .addComponent(musteriIsimAlani)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(gunAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(ayAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(yilAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addComponent(jLabel8)
                                                                .addGap(36, 36, 36)
                                                                .addComponent(jLabel7)
                                                                .addGap(0, 19, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(musteriDuzenle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(musteriSil, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(musteriIsimAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(urunIsimAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(urunFiyatAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(musteriDuzenle)
                                                .addGap(18, 18, 18)
                                                .addComponent(musteriSil)))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(urunAdediAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(gunAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ayAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(yilAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void musteriTablosuMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedrow = musteriTablosu.getSelectedRow();
        musteriIsimAlani.setText(model.getValueAt(selectedrow, 0).toString());
        urunIsimAlani.setText(model.getValueAt(selectedrow, 1).toString());
        urunFiyatAlani.setText(model.getValueAt(selectedrow, 2).toString());
        urunAdediAlani.setText(model.getValueAt(selectedrow, 3).toString());

        gunAlani.setText(model.getValueAt(selectedrow, 6).toString());
        ayAlani.setText(model.getValueAt(selectedrow, 5).toString());
        yilAlani.setText(model.getValueAt(selectedrow, 7).toString());

    }


    private void musteriDuzenleActionPerformed(java.awt.event.ActionEvent evt) {
        String musteriAd = musteriIsimAlani.getText();
        String urunAd = urunIsimAlani.getText();
        int urunFiyat = Integer.parseInt(urunFiyatAlani.getText());
        int urunAded = Integer.parseInt(urunAdediAlani.getText());
        int gun = Integer.parseInt(gunAlani.getText());
        int ay = Integer.parseInt(ayAlani.getText());
        int yil = Integer.parseInt(yilAlani.getText());

        int selectedrow = musteriTablosu.getSelectedRow();

        String musteriIsmi = (String) model.getValueAt(selectedrow,1);
        MusteriEkle m = new MusteriEkle();

        musteriekle.musteriGuncelle(musteriAd,urunAd,urunFiyat,urunAded,gun,ay,yil);

        musteriGoruntule musteriGoruntule = new musteriGoruntule();
        musteriGoruntule.setVisible(true);



    }


    private void musteriSilActionPerformed(java.awt.event.ActionEvent evt) {

        int selectedrow = musteriTablosu.getSelectedRow();

        String musteriIsmi = (String) model.getValueAt(selectedrow,0);
        MusteriEkle m = new MusteriEkle();
        musteriekle.musteriSil(musteriIsmi);

        musteriGoruntule musteriGoruntule = new musteriGoruntule();
        musteriGoruntule.setVisible(true);

    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musteriGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musteriGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musteriGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musteriGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musteriGoruntule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField ayAlani;
    private javax.swing.JTextField gunAlani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton musteriDuzenle;
    private javax.swing.JTextField musteriIsimAlani;
    private javax.swing.JButton musteriSil;
    private javax.swing.JTable musteriTablosu;
    private javax.swing.JTextField urunAdediAlani;
    private javax.swing.JTextField urunFiyatAlani;
    private javax.swing.JTextField urunIsimAlani;
    private javax.swing.JTextField yilAlani;
    // End of variables declaration
}
